linkedin/css-blocks

- README.md
- packages/@css-blocks/website/src/pages/Home/index.tsx
The zombie emoji doesn't look quite right on Windows.
I assume any system that doesn't have the male/female zombie modifiers will also have this issue.
This makes the zombie gender-neutral so readers can focus on the dead code elimination part 😉
> Change the zombie emoji

- packages/@css-blocks/core/README.md
> You can read more about these style tracking methods on the [ElementAnalysis API documentation][TODO]
Currently, this part of the documentation is marked as a TODO. If the following link is correct, could it instead point here? http://css-blocks.com/api/classes/_css_blocks_core.elementanalysis.html
> Update link to ElementAnalysis docs

- ARCHITECTURE.md
`https://github.com/linkedin/css-blocks/blob/master` is not a valid URL, and
it breaks the navigation inside the architecture document where the README is linked to.
> Add a specific README URL in architecture doc

- packages/@css-blocks/jsx/README.md
My guess is that for `.myClass[state|rootState]` the code would be `styles.myClass.rootState()`, but the code is `styles.rootState()`, so I believe the documentation comment is incorrect and should change as stated by the PR.
> Fixes root state comment on README

- packages/@css-blocks/jsx/README.md
- packages/@css-blocks/webpack/README.md
I made the JSX consistent with the Webpack examples.
Also brought more "ghost"/"undefined" variables into the snippets. I am not sure if this is more confusing but it still follows the consistency of using create-react-app varialbes (i.e. the paths.indexJs).
> Improve docs for webpack and jsx

- .travis.yml
- package.json
- packages/@css-blocks/broccoli/package.json
- packages/@css-blocks/broccoli/src/Analyze.ts
- packages/@css-blocks/broccoli/test/Aggregate.ts
- packages/@css-blocks/broccoli/test/Analyze.ts
- packages/@css-blocks/ember-cli/index.js
- packages/@css-blocks/ember-cli/tests/dummy/app/package.json
- packages/@css-blocks/ember-cli/tests/dummy/app/router.js
- packages/@css-blocks/ember-cli/tests/dummy/app/styles/node-modules-resolution.block.css
- packages/@css-blocks/ember-cli/tests/dummy/app/templates/application.hbs
- packages/@css-blocks/ember-cli/tests/dummy/app/templates/node-modules-resolution.hbs
- packages/@css-blocks/ember-cli/tests/dummy/lib/in-repo-addon/addon/package.json
- packages/@css-blocks/ember-cli/tests/dummy/lib/in-repo-addon/app/package.json
- packages/@css-blocks/ember-cli/tests/dummy/lib/in-repo-addon/package.json
- packages/@css-blocks/ember-cli/tests/dummy/lib/in-repo-engine/addon/package.json
- packages/@css-blocks/ember-cli/tests/dummy/lib/in-repo-engine/package.json
- packages/@css-blocks/ember-cli/tests/dummy/lib/in-repo-lazy-engine/addon/package.json
- packages/@css-blocks/ember-cli/tests/dummy/lib/in-repo-lazy-engine/package.json
- packages/@css-blocks/glimmer/test/recursive-template-dependencies-test.ts
- packages/@css-blocks/glimmer/test/template-dependencies-test.ts
- packages/@css-blocks/jsx/src/Analyzer/index.ts
- yarn.lock
Fixes a bug where changes are occasionally not picked up.
> fix(broccoli): Rebuild diffs input changes and output patch separately.

- packages/@css-blocks/core/src/TemplateRewriter/StyleMapping.ts
- packages/@css-blocks/ember-cli/tests/dummy/app/styles/ember-builtins.block.css
- packages/@css-blocks/ember-cli/tests/dummy/app/templates/ember-builtins.hbs
- packages/@css-blocks/ember-cli/tests/integration/template-discovery-test.js
- packages/@css-blocks/glimmer/src/Analyzer.ts
- packages/@css-blocks/glimmer/src/ClassnamesHelperGenerator.ts
- packages/@css-blocks/glimmer/src/ElementAnalyzer.ts
- packages/@css-blocks/glimmer/src/EmberBuiltins.ts
- packages/@css-blocks/glimmer/src/Rewriter.ts
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-link-to/external.css
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-link-to/stylesheet.css
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-link-to/template.hbs
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-link-to/util.css
- packages/@css-blocks/glimmer/test/template-rewrite-test.ts
In Ember, the built in `{{link-to}}` component internally applies an `active`, `loading` or `disabled` class when the application's current active route matches the route, is loading, or the link is disabled. In CSS Blocks, we need a method to style these internally managed `{{link-to}}` states. 
The built in `{{link-to}}` helper has an attributes that enable developers to override the active, loading and disabled classes used by the component. A small change to the Glimmer analyzer and rewriter enable us to rewrite `{{link-to}}` like any other elements, but allow CSS Blocks to pass custom state styles.
Any `{{link-to}}` component discovered with one or more CSS Blocks classes applied to it will automatically have any `[state|active]`, `[state|loading]`, or `[state|disabled]` styles …
> feat(glimmer): {{link-to}} integration.

- packages/@css-blocks/broccoli/src/Analyze.ts
- packages/@css-blocks/core/src/BlockCompiler/ConflictResolver.ts
- packages/@css-blocks/core/src/BlockParser/BlockFactory.ts
- packages/@css-blocks/core/src/BlockParser/BlockParser.ts
- packages/@css-blocks/core/src/BlockParser/features/assert-foreign-global-attribute.ts
- packages/@css-blocks/core/src/BlockParser/features/export-blocks.ts
- packages/@css-blocks/core/src/BlockParser/features/extend-block.ts
- packages/@css-blocks/core/src/BlockParser/features/implement-block.ts
- packages/@css-blocks/core/src/BlockSyntax/parseBlockDebug.ts
- packages/@css-blocks/core/src/BlockTree/Block.ts
- packages/@css-blocks/core/src/BlockTree/RulesetContainer.ts
- packages/@css-blocks/core/src/importing/NodeJsImporter.ts
- packages/@css-blocks/core/src/util/propertyParser.ts
- packages/@css-blocks/core/test/BlockParser/import-export-test.ts
- packages/@css-blocks/core/test/block-inheritance-test.ts
- packages/@css-blocks/core/test/resolution-test.ts
- ConflictResolver now takes shorthands into consideration.
- PropertyParser has special cases for border and font-family because of bugs in source package.
- fix: Export syntax now allows for immediate re-export from file path.
- Added more debug statements.
- Fix Broccoli bug to only remove files from tmp directory output.
> fix: Properly output conflict resolutions for shorthands.

- packages/@css-blocks/webpack/src/Plugin.ts
- packages/@css-blocks/webpack/test/plugin-test.ts
- packages/@css-blocks/webpack/test/util/execTest.ts
- packages/@css-blocks/webpack/test/util/testPaths.ts
This fix filters out fake paths injected by the dev server. Doing so prevents the throwing of ENOENT errors when the Analyzer tries to open those fake paths. Fixes #163.
I've tested this manually by linking it into a project that uses webpack-dev-server and observing that compilation succeeds where it had previously failed.
The test I added fails with `Module build failed: Error: No rewriter` as do all but one of the existing Plugin tests when unskipped. (The outlier fails with a different error.) Since the existing tests have been skipped, I figure it's okay to do the same with this one.
> fix(webpack): Compatibility w/ webpack-dev-server.

- .travis.yml
- packages/@css-blocks/cli/package.json
- yarn.lock
node-sass 4.12 has support for node 12 so we can remove the allowed failure in CI.
> chore: Update dev dep node-sass to 4.12.0 for node 12 support.

- packages/@css-blocks/cli/README.md
- packages/@css-blocks/cli/package.json
- packages/@css-blocks/cli/src/index.ts
- packages/@css-blocks/cli/test/cli-test.ts
- packages/@css-blocks/cli/test/fixtures/.gitignore
- packages/@css-blocks/cli/test/fixtures/importing/alias.block.css
- packages/@css-blocks/cli/test/fixtures/importing/node_modules/block-module/blocks/font.block.css
- packages/@css-blocks/cli/test/fixtures/importing/node_modules/block-module/index.block.css
- packages/@css-blocks/cli/test/fixtures/importing/node_modules/block-module/package.json
- packages/@css-blocks/cli/test/fixtures/importing/npm.block.css
- packages/@css-blocks/core/src/BlockParser/BlockFactory.ts
- packages/@css-blocks/core/src/BlockParser/BlockParser.ts
- packages/@css-blocks/core/src/configuration/resolver.ts
This patch provides CLI options to allow imports to come from node_modules and to define import aliases.
The tests for this feature change the working directory which exposed that the current working directory was being cached at the time of import.
> [cli] Add support for importing from npm modules and using import aliases.

- packages/@css-blocks/runtime/src/ExpressionContainer.ts
- packages/@css-blocks/runtime/src/constructor.ts
- packages/@css-blocks/runtime/src/runtime.ts
- packages/@css-blocks/runtime/test/expression-test.ts
Working binary runtime package. Currently clocks in at under 681 bytes minified and will greatly reduce the possibility for template bloat on rewrite. See https://github.com/linkedin/css-blocks/issues/47 for implementation details. To complete:
I expect that the base `ElementAnalysis` object delivered in core will proxy some version of the expression constructor to analyzers. The core rewrite transport object will then expose the three generated array parts – expression shapes array, classes array, and expressions array – to the rewriters to apply as the wish.
> Edit: this is ready to land. I'd like to tackle tasks 3, 4 and 5 in a separate PR now that this is fully functional and tested 👍
> feat: Binary runtime helper.

- packages/@css-blocks/ember-cli/index.js
Addons may provide a custom module name either as a property or a function in their config. Respect this setting.
> fix: Respect custom Ember module names.

- packages/@css-blocks/cli/src/index.ts
- packages/@css-blocks/cli/test/cli-test.ts
- packages/@css-blocks/cli/test/fixtures/basic/deep-transitive-error.block.css
- packages/@css-blocks/core/src/BlockParser/BlockParser.ts
- packages/@css-blocks/core/src/BlockParser/features/import-blocks.ts
- packages/@css-blocks/core/src/SourceLocation.ts
- packages/@css-blocks/core/src/errors.ts
When a block doesn't compile due to a downstream error in a block reference, the locations of the `@block` at-rules that brought in the failing block file are now part of the error's public interface and are displayed in the CLI error output.
The error locations are source-mapped where appropriate.
> Block import stack

- packages/@css-blocks/core/src/Analyzer/Analysis.ts
- packages/@css-blocks/core/src/BlockCompiler/index.ts
- packages/@css-blocks/core/src/BlockSyntax/BlockPath.ts
- packages/@css-blocks/core/src/BlockTree/Block.ts
- packages/@css-blocks/core/test/BlockSyntax/block-path-test.ts
- packages/@css-blocks/core/test/block-interface-test.ts
- packages/@css-blocks/core/test/validations/property-conflict-validator-test.ts
- packages/@css-blocks/glimmer/src/Analyzer.ts
- packages/@css-blocks/glimmer/src/ElementAnalyzer.ts
- packages/@css-blocks/glimmer/src/Rewriter.ts
- packages/@css-blocks/glimmer/test/fixtures/readme-app/src/ui/components/page-layout/stylesheet.css
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-dynamic-classes/stylesheet.css
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-dynamic-states/stylesheet.css
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-link-to/stylesheet.css
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-multiple-blocks/stylesheet.css
- packages/@css-blocks/glimmer/test/stylesheet-analysis-test.ts
Previously, the block's interface constituted of all of its imported blocks as well as the classes and states defined on the block.
Now, the block's public interface will consist of only that which is explicitly exported using @export
> feat: Respect explicit exports for a block interface.

- packages/@css-blocks/language-server/src/Server.ts
- packages/@css-blocks/language-server/src/documentLinksProviders/blockLinkProvider.ts
- packages/@css-blocks/language-server/src/serverCapabilities.ts
- packages/@css-blocks/language-server/src/test/server-test.ts
For css and sass, vscode provides a "jump to file" feature for @import and
`url()` statements. For css-blocks, we only need to add this support for
custom "at rules" (@block, @export). For `url()`, the builtin vscode css
language server should still be providing that functionality.
> feat: Add document links provider.

- packages/@css-blocks/language-server/package.json
- packages/@css-blocks/language-server/src/Server.ts
- packages/@css-blocks/language-server/src/completionProviders/emberCompletionProvider.ts
- packages/@css-blocks/language-server/src/createBlockFactory.ts
- packages/@css-blocks/language-server/src/definitionProviders/emberDefinitionProvider.ts
- packages/@css-blocks/language-server/src/documentLinksProviders/blockLinkProvider.ts
- packages/@css-blocks/language-server/src/eventHandlers/documentContentChange.ts
- packages/@css-blocks/language-server/src/pathTransformers/EmberClassicTransformer.ts
- packages/@css-blocks/language-server/src/pathTransformers/PathTransformer.ts
- packages/@css-blocks/language-server/src/run.ts
- packages/@css-blocks/language-server/src/test/fixtures/ember-classic-scss/css-blocks.config.js
- packages/@css-blocks/language-server/src/test/fixtures/ember-classic-scss/styles/blocks/block-with-errors.block.scss
- packages/@css-blocks/language-server/src/test/fixtures/ember-classic-scss/styles/blocks/utils.block.scss
- packages/@css-blocks/language-server/src/test/fixtures/ember-classic-scss/styles/components/a.block.scss
- packages/@css-blocks/language-server/src/test/fixtures/ember-classic-scss/styles/components/import-completions.block.scss
- packages/@css-blocks/language-server/src/test/fixtures/ember-classic-scss/templates/components/a.hbs
- packages/@css-blocks/language-server/src/test/server-test-scss.ts
- packages/@css-blocks/language-server/src/test/server-test.ts
- packages/@css-blocks/language-server/src/types/glob-escape.d.ts
- packages/@css-blocks/language-server/src/util/blockUtils.ts
- packages/@css-blocks/language-server/src/util/diagnosticsUtils.ts
- packages/@css-blocks/language-server/src/util/hbsCompletionProvider.ts
- packages/@css-blocks/language-server/src/util/hbsDefinitionProvider.ts
- packages/@css-blocks/language-server/src/util/hbsUtils.ts
- packages/@css-blocks/language-server/src/util/pathTransformer.ts
- yarn.lock
This PR adds basic support for any preprocessors that are set up in the css-blocks' configuration file. Because any extension is technically supported, we have to go to the disk to see what files actually exist according to expected naming conventions so that we can return the path to the correct file. Stylesheets that appear to be block files (e.g. named `*.block.*`) but aren't supported by the preprocessor configuration are basically ignored right now because otherwise CSS Blocks would just throw an error if we tried to parse it.
TODO:
> feat: Basic preprocessor support.

- packages/@css-blocks/broccoli/test/Analyze.ts
- packages/@css-blocks/broccoli/test/Transport.ts
- packages/@css-blocks/core/src/Analyzer/Analyzer.ts
- packages/@css-blocks/core/test/opticss-test.ts
- packages/@css-blocks/core/test/template-analysis-test.ts
- packages/@css-blocks/core/test/validations/attribute-group-validator-test.ts
- packages/@css-blocks/core/test/validations/attribute-parent-validator-test.ts
- packages/@css-blocks/core/test/validations/class-pairs-validator-test.ts
- packages/@css-blocks/core/test/validations/property-conflict-validator-test.ts
- packages/@css-blocks/core/test/validations/root-class-validator-test.ts
- packages/@css-blocks/core/test/validations/validator-test.ts
- packages/@css-blocks/ember-cli/index.js
- packages/@css-blocks/glimmer/src/Analyzer.ts
- packages/@css-blocks/glimmer/test/stylesheet-analysis-test.ts
- packages/@css-blocks/glimmer/test/template-rewrite-test.ts
- packages/@css-blocks/jsx/src/Analyzer/index.ts
- packages/@css-blocks/language-server/package.json
- packages/@css-blocks/language-server/src/Server.ts
- packages/@css-blocks/language-server/src/serverCapabilities.ts
- packages/@css-blocks/language-server/src/util/createFocusPath.ts
- packages/@css-blocks/webpack/test/configs/basicConfig.ts
- packages/@css-blocks/webpack/test/configs/templateConfig.ts
- yarn.lock
Some preliminary refactoring to prepare for using the analyzer to get all references to class.
> Phase 1 of "find references"

- packages/@css-blocks/ember-cli/testem.js
- packages/@css-blocks/ember-cli/tests/dummy/app/initializers/main.js
- packages/@css-blocks/ember-cli/tests/test-helper.js
The test logs for the ember-cli package are currently very noisy. This
silences the jquery deprecation warning and removes extraneous tests
for lint errors and ember onerror.
> chore: Clean up ember test logs.

- packages/@css-blocks/ember-cli/ember-cli-build.js
- packages/@css-blocks/ember-cli/package.json
- packages/@css-blocks/ember-cli/tests/dummy/lib/in-repo-engine/package.json
This fixes the invalid config error in ember-cli>v3.15.
> fix: Removing invalid paths from the package.json.

- README.md
This fixes the broken badge in the readme.
> fix: update Travis CI badge URL

- packages/@css-blocks/glimmer/.vscode/launch.json
- packages/@css-blocks/glimmer/src/Analyzer.ts
- packages/@css-blocks/glimmer/src/ClassnamesHelperGenerator.ts
- packages/@css-blocks/glimmer/src/ElementAnalyzer.ts
- packages/@css-blocks/glimmer/src/EmberBuiltins.ts
- packages/@css-blocks/glimmer/src/Rewriter.ts
- packages/@css-blocks/glimmer/src/utils.ts
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-style-helper/header.css
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-style-helper/stylesheet.css
- packages/@css-blocks/glimmer/test/fixtures/styled-app/src/ui/components/with-style-helper/template.hbs
- packages/@css-blocks/glimmer/test/template-rewrite-test.ts
There is a new synthetic helper for css-blocks in glimmer and ember applications called `style-of`.
Original Specification is at: https://github.com/linkedin/css-blocks/issues/383
The parameters and hash arguments to a `style-of` helper invocation are analyzed as if the helper invocation is an element or component invocation. The arguments to `style-of` can be dynamic in the same way that attributes can be dynamic.
The return value of the `style-of` helper is a string that can be set to an html `class` attribute. This value should be considered opaque. Do not try to manipulate it or depend on the value inside it.
Merging the class names from CSS Blocks with class names from styles not managed by CSS Blocks may result in unexpected behavior, especially with opticss enabled.
Closes #383.
> Add style-of helper for glimmer.

- css-blocks.code-workspace
- packages/@css-blocks/eyeglass/CHANGELOG.md
- packages/@css-blocks/eyeglass/README.md
- packages/@css-blocks/eyeglass/package.json
- packages/@css-blocks/eyeglass/src/index.ts
- packages/@css-blocks/eyeglass/test/mocha.opts
- packages/@css-blocks/eyeglass/test/package-test.ts
- packages/@css-blocks/eyeglass/tsconfig.json
- packages/@css-blocks/eyeglass/tslint.cli.json
- packages/@css-blocks/eyeglass/tslint.json
- packages/@css-blocks/eyeglass/tslint.release.json
- yarn.lock
Fixes #398 
Should be a cleaner TS implementation than my previous PR (thanks for the feedback and help using Namespaces as types). I'm using Sinon spies in the tests, and because of that found I didn't need to use the module importer mock you mentioned (as rather than testing all of css-blocks in the unit tests I'm just testing what _this package_  takes in and puts out, as well as that the created functions are called). 
Code test coverage is 100%, which is nice.
> feat(eyeglass): Adds new package that enables simple Eyeglass support.

- packages/@css-blocks/core/src/BlockParser/index.ts
- packages/@css-blocks/core/src/BlockParser/preprocessing.ts
- packages/@css-blocks/core/src/BlockTree/RulesetContainer.ts
- packages/@css-blocks/eyeglass/README.md
- packages/@css-blocks/eyeglass/src/index.ts
- packages/@css-blocks/eyeglass/test/fixtures/package-1/one.block.scss
- packages/@css-blocks/eyeglass/test/fixtures/package-2/two.block.scss
- packages/@css-blocks/eyeglass/test/package-test.ts
There is now a core data type for preprocessors that conditionally process a stylesheet. The motivation for this is to allow libraries to expose a preprocessor integration for their specific Sass + Eyeglass library.
This allows the library to maintain some semblance of control over how the compilation is performed, in case that is important to that module (E.g. the precision value for Sass or exposing assets via eyeglass).
There's a base class for libraries to use (`DirectoryScopedPreprocessor`), and a helper function for applications that integrates all of the preprocessor adaptors into a single processor that supplies sass, eyeglass, and application default options.
If the `DirectoryScopedPreprocessor` isn't sufficient for a library's needs, they can implement the `PreprocessorProvider` …
> Optional Preprocessors & library/application API contract.

- packages/@css-blocks/core/src/importing/BaseImporter.ts
- packages/@css-blocks/core/src/importing/NodeJsImporter.ts
- packages/@css-blocks/core/test/fixtures/compiledFileImporting/embedded/nav.css
- packages/@css-blocks/core/test/fixtures/compiledFileImporting/expectedResults/expectedCssContents.txt
- packages/@css-blocks/core/test/fixtures/compiledFileImporting/expectedResults/expectedDfnContents.txt
- packages/@css-blocks/core/test/fixtures/compiledFileImporting/externaldef/nav.block.css
- packages/@css-blocks/core/test/fixtures/compiledFileImporting/externaldef/nav.css
- packages/@css-blocks/core/test/importing-test.ts
- Update import method in NodeJSImporter to support Compiled CSS files.
This update supports both inline definitions and definition files.
- Update tests to validate changes.
> feat: Compiled CSS importing in NodeJSImporter.

- packages/@css-blocks/core/src/BlockParser/BlockParser.ts
- packages/@css-blocks/core/src/BlockParser/features/add-interface-indexes.ts
- packages/@css-blocks/core/src/BlockTree/Style.ts
- packages/@css-blocks/core/test/BlockParser/definition-file-processing-test.ts
- When processing definition files, recognize and set the interface
index on style nodes in the Block. As with block-class, if each style
node found has not declared an interface-index by the end of processing,
it's an error.
- Test coverage for ensuring block-interface-index is declared.
> feat: Parse and set block-interface-index

- packages/@css-blocks/core/src/BlockCompiler/index.ts
- packages/@css-blocks/core/src/BlockParser/features/add-preset-selectors.ts
- packages/@css-blocks/core/src/BlockParser/features/discover-name.ts
- packages/@css-blocks/core/src/importing/NodeJsImporter.ts
- packages/@css-blocks/core/test/BlockParser/block-name-test.ts
- packages/@css-blocks/core/test/acceptance/DfnFilesFullWorkflow.ts
- packages/@css-blocks/core/test/util/MockImportRegistry.ts
This PR includes two commits...
**fix: Allow quotes surrounding block-name.**
Definition file output wraps the block-name in quotes, but there are
existing rules in CSS Blocks disallowing this. This removes this rule,
using stripQuotes() to unwrap the block-name value. With this change,
block-name, block-id, and block-class will all behave in the same way.
**test: Definition Files Basic Acceptance Tests.**
- Test the full workflow of working with definition files. From a source
block file, compile it into css and definition data, then reconstitute
the block and validate the name, GUID, and properties match.
- Tests for both external definition files and embedded definition data.
- Update the mock importer to recognize embedded definition data.
- Add some comments to MockImporter and the …
> Definition File Full Workflow - Acceptance Tests

- packages/@css-blocks/ember-app/README.md
- packages/@css-blocks/ember-app/package.json
- packages/@css-blocks/ember-app/src/index.ts
- packages/@css-blocks/ember-app/test/mocha.opts
- packages/@css-blocks/ember-app/tsconfig.json
- packages/@css-blocks/ember-app/tslint.cli.json
- packages/@css-blocks/ember-app/tslint.json
- packages/@css-blocks/ember-app/tslint.release.json
- private-packages/fixtures-ember-v2/ember-app.code-workspace
- private-packages/fixtures-ember-v2/ember-app/package.json
- private-packages/fixtures-ember-v2/ember-lazy-engine/package.json
Depends on: #457 
- Basic scaffolding and stubs for the ember-app addon, borrowed from the @css-blocks/ember addon.
- Add @css-blocks/ember-app as a dependency to ember v2 fixtures.
- Added names to ember-app VSCode workspace to disambiguate between the ember-app addon and the ember-app fixture.
> Establish ember-app addon!

- .travis.yml
- packages/@css-blocks/ember-app/package.json
- packages/@css-blocks/ember-app/runtime/app/services/StyleEvaluator.ts
- packages/@css-blocks/ember-app/runtime/app/services/StyleResolver.ts
- packages/@css-blocks/ember-app/runtime/app/services/css-blocks.ts
- packages/@css-blocks/ember-app/src/AggregateRewriteData.ts
- packages/@css-blocks/ember-app/src/RuntimeDataGenerator.ts
- packages/@css-blocks/ember-app/test/runtime-data-generator-test.ts
- packages/@css-blocks/ember/src/TemplateAnalyzingRewriter.ts
- packages/@css-blocks/ember/test/template-rewrite-test.ts
This change greatly simplifies the per-element rewrite for elements that have dynamic attribute values. In the element rewrite we no longer enumerate all the attribute values as possible styles and we don't enumerate the specific values as part of the switch condition. Instead we just reference the attribute as being a switch condition and let the runtime fill in the possible values from new information that is passed in for the aggregate rewrite data.
The aggregate rewrite data is more explicit than it strictly needs to be, the rewrite code could do some sort of string manipulation in order to construct the attribute value style name instead of looking it up in a table. However that solution would preclude a later optimization where we optimize away the strings and replace them with …
> Simplify Dynamic Attribute Rewrite

- packages/@css-blocks/eyeglass/package.json
- packages/@css-blocks/eyeglass/src/index.ts
- packages/@css-blocks/eyeglass/test/package-test.ts
- yarn.lock
In a directory scoped processor, we want to treat the root directory of the processor as the eyeglass root. We override any root setting that the application's configuration has provided, but we allow the root to be overridden in the processor's `setupOptions()` method.
Usually the application's root is good enough for compilation, but there are situations where the directory structures don't align and it's important for the scoped processor to have its root take precedence. Namely: `yarn link`'ed development requires this.
> Set eyeglass root within a directory-scoped processor.

- packages/@css-blocks/ember-app/src/broccoli-plugin.ts
- packages/@css-blocks/ember-utils/src/EmberAnalysis.ts
- packages/@css-blocks/ember/src/AnalyzingRewriteManager.ts
- packages/@css-blocks/ember/src/CSSBlocksTemplateCompilerPlugin.ts
Now that we have synchronous block loading we don't have to go parse all the blocks just in case we might need them during template compilation.[
This also fixes a runtime error that I occured in the situation where an application doesn't have any block files.
> Simplify block lookups for a template
